name: scanner_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  google_mlkit_text_recognition: ^0.11.0
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  image_picker: ^1.1.2  
  image_editor_plus: ^1.0.6
  google_mlkit_entity_extraction: ^0.11.0
  camera: ^0.11.0+2
  flutter_animate: ^4.5.0
  image_gallery_saver: ^2.0.3
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
assets:
  - images/
